name: Comment-Triggered C++ Analysis

on:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/analyze-cpp')
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
      pr_number: ${{ steps.check.outputs.pr_number }}
      
    steps:
    - name: Check comment and permissions
      id: check
      run: |
        # Check if commenter has write permissions
        COMMENTER="${{ github.event.comment.user.login }}"
        echo "Comment by: $COMMENTER"
        echo "Comment: ${{ github.event.comment.body }}"
        
        # You can add permission checks here if needed
        # For now, allow anyone to trigger (you might want to restrict this)
        
        echo "should_run=true" >> $GITHUB_OUTPUT
        echo "pr_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
    
    - name: Add reaction to comment
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.reactions.createForIssueComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: ${{ github.event.comment.id }},
            content: 'rocket'
          });

  run-analysis:
    needs: check-comment
    if: needs.check-comment.outputs.should_run == 'true'
    uses: ./.github/workflows/cpp-guidelines-check.yml
    with:
      pr_number: ${{ needs.check-comment.outputs.pr_number }} 